platform :ios, '20.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'


def flutter_root
  generated = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise "#{generated} missing. Run `flutter pub get`." unless File.exist?(generated)
  File.foreach(generated) do |line|
    m = line.match(/FLUTTER_ROOT\=(.*)/)
    return m[1].strip if m
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Keep the platform consistent
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '20.0'
      # ✅ Force all pods (including FirebaseCoreInternal) to Swift 5.10 on Xcode 15.x
      config.build_settings['SWIFT_VERSION'] = '5.10'
      # Optional: quiet some warnings
      # config.build_settings['OTHER_SWIFT_FLAGS'] = '-Xfrontend -disable-availability-checking'
    end
  end
end